**1. Importei as bibliotecas necessárias**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

**2. Importei os dados**

In [2]:
data = pd.read_csv('data.csv')
data.head(10)

Bankrupt?   ROA(C) before interest and depreciation before interest  \
0          1                                           0.370594          
1          1                                           0.464291          
2          1                                           0.426071          
3          1                                           0.399844          
4          1                                           0.465022          
5          1                                           0.388680          
6          0                                           0.390923          
7          0                                           0.508361          
8          0                                           0.488519          
9          0                                           0.495686          

    ROA(A) before interest and % after tax  \
0                                 0.424389   
1                                 0.538214   
2                                 0.499019   
3                                 0.451265   
4                                 0.538432   
5                                 0.415177   
6                                 0.445704   
7                                 0.570922   
8                                 0.545137   
9                                 0.550916   

    ROA(B) before interest and depreciation after tax  \
0                                           0.405750    
1                                           0.516730    
2                                           0.472295    
3                                           0.457733    
4                                           0.522298    
5                                           0.419134    
6                                           0.436158    
7                                           0.559077    
8                                           0.543284    
9                                           0.542963    

    Operating Gross Margin   Realized Sales Gross Margin  \
0                 0.601457                      0.601457   
1                 0.610235                      0.610235   
2                 0.601450                      0.601364   
3                 0.583541                      0.583541   
4                 0.598783                      0.598783   
5                 0.590171                      0.590251   
6                 0.619950                      0.619950   
7                 0.601738                      0.601717   
8                 0.603612                      0.603612   
9                 0.599209                      0.599209   

    Operating Profit Rate   Pre-tax net Interest Rate  \
0                0.998969                    0.796887   
1                0.998946                    0.797380   
2                0.998857                    0.796403   
3                0.998700                    0.796967   
4                0.998973                    0.797366   
5                0.998758                    0.796903   
6                0.998993                    0.797012   
7                0.999009                    0.797449   
8                0.998961                    0.797414   
9                0.999001                    0.797404   

    After-tax net Interest Rate   Non-industry income and expenditure/revenue  \
0                      0.808809                                      0.302646   
1                      0.809301                                      0.303556   
2                      0.808388                                      0.302035   
3                      0.808966                                      0.303350   
4                      0.809304                                      0.303475   
5                      0.808771                                      0.303116   
6                      0.808960                                      0.302814   
7                      0.809362                                      0.303545   
8                      0.809338    

**3. Dividi as variáveis em Dependente e Independente**

In [3]:
X = data.drop(['Bankrupt?'], axis = 1)
y = data['Bankrupt?']

**4. Dividi os dados em treino e teste**

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = .2, random_state = 42)

**5. Treinei um modelo de Regressão Logística**

In [8]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression(max_iter = 1000)
logmodel.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

**6. Avaliei o modelo**

In [13]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
predictions = logmodel.predict(X_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1313
           1       0.00      0.00      0.00        51

    accuracy                           0.96      1364
   macro avg       0.48      0.50      0.49      1364
weighted avg       0.93      0.96      0.94      1364

[[1311    2]
 [  51    0]]
0.9611436950146628


**7. Treinei um modelo de Árvore de Decisão**

In [10]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree.fit(X_train, y_train)

DecisionTreeClassifier()

**8. Avaliei o modelo**

In [15]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
predictions = dtree.predict(X_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1313
           1       0.31      0.31      0.31        51

    accuracy                           0.95      1364
   macro avg       0.64      0.64      0.64      1364
weighted avg       0.95      0.95      0.95      1364

[[1277   36]
 [  35   16]]
0.9479472140762464


**9. Treinei um modelo de Random Forest**

In [16]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 100)
rfc.fit(X_train, y_train)

RandomForestClassifier()

**10. Avaliei o modelo**

In [17]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
predictions = rfc.predict(X_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      1313
           1       0.90      0.18      0.30        51

    accuracy                           0.97      1364
   macro avg       0.93      0.59      0.64      1364
weighted avg       0.97      0.97      0.96      1364

[[1312    1]
 [  42    9]]
0.968475073313783


**11. Treinei um modelo de SVM**

In [18]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(X_train, y_train)

SVC()

**12. Avaliei o modelo**

In [19]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
predictions = svc.predict(X_test)
print(classification_report(y_test, predictions))
print(confusion_matrix(y_test, predictions))
print(accuracy_score(y_test, predictions))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      1313
           1       0.00      0.00      0.00        51

    accuracy                           0.96      1364
   macro avg       0.48      0.50      0.49      1364
weighted avg       0.93      0.96      0.94      1364

[[1313    0]
 [  51    0]]
0.9626099706744868


C:\Users\estagiario1.extensao\PycharmProjects\bankruptcy_prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\estagiario1.extensao\PycharmProjects\bankruptcy_prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\estagiario1.extensao\PycharmProjects\bankruptcy_prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` pa

**13. Criei um dataframe comparando os resultados**

In [23]:
models = pd.DataFrame({
    'Model': ['Logistic Regression', 'Decision Tree', 'Random Forest', 'SVM'],
    'Score': [accuracy_score(y_test, logmodel.predict(X_test)), accuracy_score(y_test, dtree.predict(X_test)), accuracy_score(y_test, rfc.predict(X_test)), accuracy_score(y_test, svc.predict(X_test))]
})
models.sort_values(by = 'Score', ascending = False)

Model     Score
2        Random Forest  0.968475
3                  SVM  0.962610
0  Logistic Regression  0.961144
1        Decision Tree  0.947947

**14. Conclusão**
O modelo Random Forest foi o que obteve o melhor resultado, com 97% de acurácia. Logo, exportaremos ele para um arquivo .pkl para ser utilizado em produção.

In [24]:
import pickle
pickle.dump(rfc, open('model.pkl', 'wb'))